### ISSUE TITLE
Latest version does not show call stack for exceptions

### ISSUE THREAD

**Issue by UnoSD** [MoiraeSoftware/myriad#63]
I have recently upgraded from 0.2.8 to 0.4.0.

I used to get the full stack trace in the logs on exceptions, now, even with --verbose, I only get the error message.

I also tried to attach the debugger and didn't hit the exception (but that may be an issue with JetBrains Rider, I need to investigate)

Thank you for this library.

**Comment by 7sharp9** [comment]
Hmm, yeah this commit changed the behaviour so that the euro becomes part of the output: https://github.com/MoiraeSoftware/myriad/commit/98257af1fc7ec303940ada55feec13ea31fe377e#diff-dde16575788240cf6938e1cfac58d7f4

At the very least we need to emit the error fully with stack trace on verbose.   Im not sure I like the error being output not the AST, thoughts?

**Comment by UnoSD** [comment]
@7sharp9 I'm not sure I'm too fussed either way. As long as the output doesn't compile, I don't mind the error (and the stack trace) in the .fs file; it may help focus more rather than digging into the build logs, but I don't mind scrolling down to find the exception, either.

**Comment by 7sharp9** [comment]
Fixed in 0.6.3
